core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("old/", include("tenantRecords.urls")),  # tenant records
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls", namespace='home')),           # UI Kits Html files
]

tenantRecords/urls.py
from tenantRecords import views
from django.conf.urls import  url
from core import settings
from django.conf.urls.static import static
from django.urls import re_path, path
from django.contrib.auth.decorators import login_required, permission_required

app_name="tenantRecords"

urlpatterns = [
    url('^logout', views.LogoutView.as_view(), name='logout'),
    url('^login', views.LoginView.as_view(), name='login'),
    url('^suites', login_required(views.SuitesAccView.as_view()), name='suitesAcc'),
    url('^suites/([0-9]{4})/$', login_required(views.SuitesAccView.as_view()), name='suitesAcc'),
    url('^rentalyears', login_required(views.RentalYearsView.as_view()), name='rentalyears'),
    url('^pendingsc', login_required(views.PendingSCView.as_view()), name='pendingsc'),
    url('^addresses', login_required(views.AddressesView.as_view()), name='addresses'),
    url('^zeropaid', login_required(views.ZeroPaidView.as_view()), name='zeropaid'),
    url('^totalreceived', login_required(views.TotalReceivedView.as_view()), name='totalreceived'),
    url('^finbreakdown', login_required(views.FinBreakdownView.as_view()), name='finbreakdown'),
    url('^contactdetails', login_required(views.ContactDetailsView.as_view()), name='contactdetails'),
    url('^savepayments', login_required(views.savepayments), name='savepayments'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/$', login_required(views.PrintableDetailView.as_view()), name='detail_printable'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/detail$', login_required(views.DetailView.as_view()), name='detail'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/offer', login_required(views.OfferView.as_view()), name='offer'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/reminder', login_required(views.ReminderView.as_view()), name='reminder'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/statements/$', login_required(views.StatementsView.as_view()), name='statements'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/letters/$', login_required(views.LetterView.as_view()), name='letters'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/revisions/$', login_required(views.RevisionsView.as_view()), name='revisions'),
    url('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/revisions/(?P<rpk>\d+[A-Z]?)/$', login_required(views.RevisionView.as_view()), name='revision'),
    url('', login_required(views.DirectoryView.as_view()), name='directory'),

]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tenantRecords/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import  Tenant, Shop, Payment
from django.views import generic
from django.views.generic import View
from django.http import *
# from django.shortcuts import render_to_response,redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from reversion.models import Version
from reversion import revisions as reversion
from django.db.models.query import QuerySet
from django.views.generic.list import ListView


class BaseView(generic.ListView):
    context_object_name = 'shops'

    def get_queryset(self):
        return Shop.objects.order_by('number')


class SuitesAccView( BaseView):
    template_name = 'tenantRecords/suitesAcc.html'
    contx = {}

    # def querysetandcontexd(self):
    #     pathlist = self.request.path.split('/')
    #     if(len(pathlist) > 3):
    #         year = self.request.path.split('/')[3]
    #         return Shop.objects.order_by('number').filter(tenancystartdate__year = year)
    #     else:
    #         return Shop.objects.order_by('number').filter(number__regex = r'[0-9][0-9][0-9]?')
    #
    # def get_context_data(self, **kwargs):
    #     return {'shops': self.querysetandcontexd(), 'payments': Payment.objects.all()}

    def get_queryset(self):
        """Return the shops within the requested year."""
        pathlist = self.request.path.split('/')
        if(len(pathlist) > 3):
            year = self.request.path.split('/')[3]
            if year:
                nextyear = str((int(year)+1)) if year else '2010'
                #return Shop.objects.order_by('number').filter(tenancystartdate__year = year)
                allshops = Shop.objects.order_by('number')
                return allshops.filter(tenancystartdate__year = year)


            # rentyearshops = allshops.filter(tenancystartdate__month = '07', tenancystartdate__year = year)
            # rentyearshops1 = allshops.filter(tenancystartdate__month = '08', tenancystartdate__year = year)
            # rentyearshops2 = allshops.filter(tenancystartdate__month = '09', tenancystartdate__year = year)
            # rentyearshops3 = allshops.filter(tenancystartdate__month = '10', tenancystartdate__year = year)
            # rentyearshops4 = allshops.filter(tenancystartdate__month = '11', tenancystartdate__year = year)
            # rentyearshops5 = allshops.filter(tenancystartdate__month = '12', tenancystartdate__year = year)
            # rentyearshops7 = allshops.filter(tenancystartdate__month = '02', tenancystartdate__year = nextyear)
            # rentyearshops6 = allshops.filter(tenancystartdate__month = '01', tenancystartdate__year = nextyear)
            # rentyearshops8 = allshops.filter(tenancystartdate__month = '03', tenancystartdate__year = nextyear)
            # rentyearshops9 = allshops.filter(tenancystartdate__month = '04', tenancystartdate__year = nextyear)
            # rentyearshops10 = allshops.filter(tenancystartdate__month = '05', tenancystartdate__year = nextyear)
            # rentyearshops11 = allshops.filter(tenancystartdate__month = '06', tenancystartdate__year = nextyear)
            # return rentyearshops | rentyearshops1 | rentyearshops2 | rentyearshops3| rentyearshops5 | rentyearshops4 | rentyearshops6 | rentyearshops7 | rentyearshops8 |rentyearshops9 | rentyearshops10 | rentyearshops11
        else:
            return Shop.objects.order_by('number').filter(number__regex = r'[0-9][0-9][0-9]?')



class AddressesView( BaseView):
    template_name = 'tenantRecords/addresses.html'

class RentalYearsView( BaseView):
    template_name = 'tenantRecords/rentalyears.html'

class ZeroPaidView( BaseView):
    template_name = 'tenantRecords/zeroreceived.html'

class TotalReceivedView( BaseView):
    template_name = 'tenantRecords/totalpaidreport.html'

    def get_queryset(self):
        """Return the last five published questions."""
        return Shop.objects.exclude(pk="011").\
            exclude(pk="107").order_by('number')

class FinBreakdownView(ListView):

    tmpshop = {}
    totalrent = 0
    model = Shop
    template_name = 'tenantRecords/finbreakdown.html'

    def get_context_data(self, **kwargs):
        self.tmpshop = Shop.objects.order_by('number').filter(number__regex = r'[0-9][0-9][0-9]?')
        for shop in self.tmpshop:
            if shop.discountedrent:
                if shop.paymentrec < shop.discountedrent:
                    shop.outrent = shop.discountedrent - shop.paymentrec
                    shop.outsc = shop.servicecharge
                elif shop.paymentrec < (shop.discountedrent + shop.servicecharge):
                    shop.outsc  = (shop.discountedrent + shop.servicecharge) - shop.paymentrec
                    shop.outrent = 0
            else:
                if shop.paymentrec < shop.rent:
                    shop.outrent = shop.rent - shop.paymentrec
                    shop.outsc = shop.servicecharge
                elif shop.paymentrec < (shop.rent + shop.servicecharge):
                    shop.outsc  = (shop.rent + shop.servicecharge) - shop.paymentrec
                    shop.outrent = 0
        context = super(FinBreakdownView, self).get_context_data(**kwargs)
        context['shops'] = self.tmpshop
        return context

class PendingSCView( BaseView):
    template_name = 'tenantRecords/pendingsc.html'

class ContactDetailsView( BaseView):
    template_name = 'tenantRecords/contactdetails.html'
    def get_queryset(self):
        return Shop.objects.order_by('tenancystartdate')

class DetailView(generic.DetailView):
    model = Shop
    #slug_field = 'number'
    template_name = 'tenantRecords/detail.html'


class OfferView(generic.DetailView):
    model = Shop
    #slug_field = 'number'
    template_name = 'tenantRecords/offerletter.html'

class ReminderView(generic.DetailView):
    model = Shop
    #slug_field = 'number'
    template_name = 'tenantRecords/reminder.html'


class PrintableDetailView(generic.DetailView):
    model = Shop
    template_name = 'tenantRecords/detail_printable.html'


class DirectoryView(BaseView):
    template_name = 'tenantRecords/directory.html'

    def get_queryset(self):
        """Return the last five published questions."""
        return Shop.objects.order_by('-number')[:5]


class StatementsView(generic.DetailView):
    template_name = 'tenantRecords/statements.html'
    model = Shop

class LetterView(generic.DetailView):
    template_name = 'tenantRecords/letters.html'
    model = Shop

class RevisionsView(generic.ListView):
    context_object_name = 'versions'
    template_name = 'tenantRecords/revisions.html'
    model = Shop

    def get_queryset(self):
        return Shop.objects.get(number=self.kwargs['pk'])


class RevisionView(generic.DetailView):
    context_object_name = 'shop'
    template_name = 'tenantRecords/revision.html'
    model = Shop

    def get_queryset(self):
        shopno, verpk = self.kwargs['pk'], self.kwargs['rpk']
        #fg = reversion.get_for_object(Shop.objects.get(number=shopno))
        #return fg[int(verpk)-1].object
        return Shop.objects.filter(number=shopno)

def savepayments(request):
    for payment in Payment.objects.all():
        payment.save()

class LogoutView(generic.View):

    def get(self, request):
        logout(request)
        return render(request, 'tenantRecords/logout.html')

class LoginView(View):

    def get(self, request):
        context = RequestContext(request)
        return render(request, 'tenantRecords/login.html')

    def post(self,request, *args, **kwargs):
        # Like before, obtain the context for the user's request.
        context = RequestContext(request)

        # If the request is a HTTP POST, try to pull out the relevant information.
        if request.method == 'POST':
            # Gather the username and password provided by the user.
            # This information is obtained from the login form.
            username = request.POST['username']
            password = request.POST['password']

            # Use Django's machinery to attempt to see if the username/password
            # combination is valid - a User object is returned if it is.
            user = authenticate(username=username, password=password)

            # If we have a User object, the details are correct.
            # If None (Python's way of representing the absence of a value), no user
            # with matching credentials was found.
            if user:
                # Is the account active? It could have been disabled.
                if user.is_active:
                    # If the account is valid and active, we can log the user in.
                    # We'll send the user back to the homepage.
                    login(request, user)
                    return HttpResponseRedirect('/records/')
                else:
                    # An inactive account was used - no logging in!
                    return HttpResponse("Your Amaro account is disabled.")
            else:
                # Bad login details were provided. So we can't log the user in.
                print( "Invalid login details: {0}, {1}".format(username, password))
                return HttpResponse("Invalid login details supplied.")

        # The request is not a HTTP POST, so display the login form.
        # This scenario would most likely be a HTTP GET.
        else:
            # No context variables to pass to the template system, hence the
            # blank dictionary object...
            return render(request, 'tenantRecords/login.html', {}, context)

tenantRecords/templates/tenantRecords/detail_printable.html
<!DOCTYPE html>
<html lang="en" class="no-js">
    {% load humanize %}
    {% load static %}
    {% include 'tenantRecords/headscripts.html' %}

	<body>
		<div class="container">
			<header>
				<h1>Gallarz Investments Ltd <span>The capital Hub - Business Partner Records </span><span>{{ shop.businessname }} - Suite {{ shop.number }}</span></h1>
                {% include 'tenantRecords/navbar.html' %}
			</header>
			<div class="component">
                <h1>Tenant Information</h1>
                <table class="">
                    <tbody>

                    <tr><th>Name</th><td>{{ shop.tenant.name }}</td></tr>
                    <tr><th>Number</th><td>{{ shop.tenant.phonenumber }}</td></tr>
                    <tr><th>Address</th><td>{{ shop.tenant.houseaddress }}</td></tr>
                    </tbody>
                </table>

                <h1>Suite Details</h1>
				<table>
                    <tbody>
                        <tr>
                            <th>Suite No</th> <td> {{ shop.businessname }} - Suite {{ shop.number }}</td>
						</tr><tr>
							<th>Rent</th> <td>{{ shop.rent | floatformat:2| intcomma  }}{% include 'tenantRecords/paymenteval.html' with val=shop.haspaidrent %}
						</tr><tr>
							<th>Service Charge</th> <td>{{ shop.servicecharge | floatformat:2| intcomma }}{% include 'tenantRecords/paymenteval.html' with val=shop.haspaidservicecharge %}
						</tr><tr>
							<th>Legal Fees</th> <td>{{ shop.legalfees | floatformat:2| intcomma }}{% include 'tenantRecords/paymenteval.html' with val=shop.haspaidlegalfees %}
						</tr><tr>
							<th>VAT</th> <td>{{ shop.vat | floatformat:2| intcomma }}</td> {% include 'tenantRecords/paymenteval.html' with val=shop.haspaidvat %}
						</tr><!--<tr>
							<th>Disount</th> <td>{{ shop.discount | floatformat:2| intcomma }}</td>
						</tr>--><tr>
							<th>Rate</th> <td>{{ shop.rate | floatformat:2| intcomma }}</td>
						</tr><tr>
							<th>Payment Recieved</th> <td style="color: darkolivegreen">{{ shop.paymentrec | floatformat:2| intcomma }}</td>
						</tr><tr>
							<th>Outstanding Payment</th> <td style="color: red">{{ shop.outstandingpayment |floatformat:2 | intcomma }}</td>
						</tr><tr>
							<th>Total</th> <td>{{ shop.totaltobepaid | floatformat:2| intcomma  }}</td>
						</tr><tr>
							<th>Tenancy Renewal Date</th> <td>{{ shop.tenancyenddate  }}</td>
						</tr>
                    <tr>
							<th>Notes</th> <td>{{ shop.notes }}</td>
						</tr>

					</tbody>
				</table>

                <h1>View Payments Made</h1>
                <table class="">
                    <tbody>
                    <tr>
                        <td> <a href="{% url 'tenantRecords:statements' shop.number%}"> Payments</a></td>
                    </tr><tr>
                        <td> <a href="{% url 'tenantRecords:letters' shop.number%}"> Letters</a></td>
                    </tr>
                    </tbody>
                </table>
			</div>

		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="{% static "tenantRecords/js/jquery.stickyheader.js" %}"></script>
		<script src="{% static "tenantRecords/js/jquery.ba-throttle-debounce.min.js" %}"></script>
	</body>
</html>

tenantRecords/templates/tenantRecords/directory.html
<!DOCTYPE html>
<html lang="en" class="no-js">
    {% load humanize %}
    {% load static %}
    {% include 'tenantRecords/headscripts.html' %}

	<body>
		<div class="container">
			<header>
				<h1>The capital Hub <span>Directory</span> </h1>
                {% include 'tenantRecords/navbar.html' %}
			</header>
			<div class="component">

                <table class="">
                    <thead>
                    <h1>What would you like to view?</h1>
                    <tr><th ><a style="color: #ffffff" href="{% url 'tenantRecords:rentalyears'%}"> Suite Records </a></th></tr>
                    <tr><th ><a style="color: #ffffff" href="{% url 'tenantRecords:pendingsc' %}"> Outstanding Service Charge Payments</a></th></tr>
                    <tr><th ><a style="color: lightskyblue" href="#">Outstanding Legal Payments(coming soon) </a></th></tr>
                    <tr><th ><a style="color: #ffffff" href="{% url 'tenantRecords:contactdetails' %}">Tenant Phone Numbers </a></th></tr>
                    <tr><th ><a style="color: #ffffff" href="{% url 'tenantRecords:addresses' %}">Tenant Addresses </a></th></tr>
                    <tr><th ><a style="color: #ffffff" href="{% url 'tenantRecords:zeropaid' %}">Zero paid </a></th></tr>
                    <tr><th ><a style="color: #ffffff" href="{% url 'tenantRecords:totalreceived' %}">All Received Payments </a></th></tr>
                    <tr><th ><a style="color: #ffffff" href="{% url 'tenantRecords:finbreakdown' %}">Fin Breakdown </a></th></tr>
                    </thead>
                </table>

				<p class="filler"></p>
			</div>

		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="{% static "tenantRecords/js/jquery.stickyheader.js" %}"></script>
		<script src="{% static "tenantRecords/js/jquery.ba-throttle-debounce.min.js" %}"></script>
	</body>
</html>

tenantRecords/templates/tenantRecords/login.html
<!DOCTYPE html>
<html lang="en" class="no-js">
    {% load humanize %}
    {% load static %}
    {% include 'tenantRecords/headscripts.html' %}

    <body>
		<div class="container">
			<header>
				<h1>The capital Hub <span> Information System </span></h1>
                {% include 'tenantRecords/navbar.html' %}
			</header>


                <div style="width: 1000px; margin: auto" id="login" >
                        <form class="form-horizontal" name="LoginForm" action="{% url  'tenantRecords:login' %}" method="post">
                        {% csrf_token %}
                        {% if next %}
                            <input type="hidden" name="next" value="{{ next }}" />
                        {% endif %}
                        <div  class="control-group">
                            <label class="control-label" for="username">Username</label>
                            <div class="controls">
                                <input type="text" id="username" name="username"  placeholder="Username">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="password">Password</label>
                            <div class="controls">
                                <input type="password" name="password" id="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="controls">
                                <button type="submit" class="btn">Login</button>
                            </div>
                        </div>
                        </form>
                    </div>
        </div>
        </body>

tenantRecords/templates/tenantRecords/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="navbar-brand"><a href="{% url 'tenantRecords:directory' %}">Home</a></li>
        <li class="navbar-brand"><a href="{% url 'tenantRecords:rentalyears' %}">Suites</a></li>
        <li class="navbar-brand"><a href="{% url 'tenantRecords:contactdetails' %}">Outstanding Payments</a></li>
        <li class="navbar-brand"><a href="{% url 'tenantRecords:addresses' %}">Addresses</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li> <a href="{% url 'tenantRecords:logout'   %}" > <span class="glyphicon glyphicon-log-out"></span>{{ user }} Logout</a></li>
        <li></li>
        {% else %}
        <li><a href="{% url 'tenantRecords:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
         {% endif %}
      </ul>
    </div>
  </div>
</nav>

tenantRecords/templates/tenantRecords/offerletter.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ shop.businessname }}</title>
</head>
    {% load humanize %}
    {% load static %}
    {% include 'tenantRecords/headscripts.html' %}

	<body>
		<div class="container">
			{% if shop.suitenumber != '0' %}
            <header>
{#				<h1>Gallarz Investments Ltd <span>The capital Hub - Business Partner Records </span><span>{{ shop.businessname }} - Suite {{ shop.suitenumber }}</span></h1>#}
{#                {% include 'tenantRecords/navbar.html' %}#}

			</header>{% endif %}
        {% if shop.suitenumber == '0' %}
            <header>
{#				<h1>Gallarz Investments Ltd <span>The capital Hub - Business Partner Records </span><span>{{ shop.businessname }} - Suite {{ shop.number }}</span></h1>#}

{#                {% include 'tenantRecords/navbar.html' %}#}

			</header>{% endif %}
			<div style="padding: 20px" class="component">
            <br>
                <br>
                <p style="font-size: 14pt"> _____________________________________________________________</p>
                <p style="font-size: 14pt"> _____________________________________________________________</p>
                <p style="font-size: 14pt"> _____________________________________________________________</p>
                <p style="font-size: 14pt"> _____________________________________________________________</p>

                <br>
                <p style="font-size: 14pt"> Dear Sir/Ma, </p>
                <h1><u>Offer Letter for Suite: {{ shop.suitenumber }} </u></h1>

                    <p style="font-size: 14pt; text-align: justify">
                    The capital Hub wishes to offer you a shop,
                        Suite No. {{ shop.suitenumber }} for rent/letting in The capital Hub located
                        at Plot 272, Bannex- Gwarinpa express way Mabushi Abuja.
                        The suite measures {{ shop.squarefeet }} sqm and at the cost {{ shop.rate | floatformat:2| intcomma }}
                        per square metre making a total of <b>{{ shop.rent | floatformat:2| intcomma  }}</b>
                        excluding VAT and other charges.
                     <br>
                     <br>

                        {% if shop.rent > shop.discountedrent %}
                            The Suite is also eligible for a discount of :  {{ shop.discount | floatformat:2| intcomma  }}.

                             <br> <br>
						{% endif %}
                        The total payable is thus the sum of: <b>{{ shop.totaltobepaid | floatformat:2| intcomma  }}</b>
                        including ALL charges.<br><br>

                        The above is subject to signing rent agreement with stated Terms and Conditions.
                    <br>
                    This offer is valid for one week after date of reciept.
                    <br>
                    <br>
                    Please accept our congratulations.
                    <br>
                    See breakdown of suite below.
                    <br>
                    </p>

{#                <table class="">#}
{#                    <tbody>#}
{##}
{#                    <tr><th>Name</th><td>{{ shop.tenant.name }}</td></tr>#}
{#                    <tr><th>Number</th><td>{{ shop.tenant.phonenumber }}</td></tr>#}
{#                    <tr><th>Address</th><td>{{ shop.tenant.houseaddress }}</td></tr>#}
{#                    </tbody>#}
{#                </table>#}

                <h1 style="font-size: 18pt">Suite Details</h1>
				<table >
                    <tbody>
                        <tr>
                            <th>Suite No</th> <td> {{ shop.businessname }} - Suite {{ shop.suitenumber }}</td>
						</tr><tr>
							<th>Rent</th> <td>{{ shop.rent | floatformat:2| intcomma  }}
						</tr>{% if shop.rent > shop.discountedrent %}<tr>
							<th>Discounted Rent</th> <td>{{ shop.discountedrent | floatformat:2| intcomma  }}
						</tr>{% endif %}{% if shop.discount %}<tr>
							<th>Disount</th> <td>{{ shop.discount | floatformat:2| intcomma }}</td>
						</tr>{% endif %}<tr>
							<th>Service Charge ({% widthratio shop.chargespercentages.servicechargepercentage  1 100 %}%)</th> <td>{{ shop.servicecharge | floatformat:2| intcomma }}
						</tr><tr>
							<th>Legal Fees ({% widthratio shop.chargespercentages.legalfeepercentage  1 100 %}%)</th> <td>{{ shop.legalfees | floatformat:2| intcomma }}
						</tr><tr>
							<th>VAT ({% widthratio shop.chargespercentages.vatpercentage  1 100 %}%)</th> <td>{{ shop.vat | floatformat:2| intcomma }}</td>
						</tr>{% if shop.balancebroughtforward %}
						  <tr>
							<th>Other Charges</th> <td>{{ shop.balancebroughtforward | floatformat:2| intcomma }}</td>
						</tr>{% endif %}<tr>
							<th>Rate</th> <td>{{ shop.rate | floatformat:2| intcomma }}</td>
						</tr><tr>
							<th>Square Meters</th> <td>{{ shop.squarefeet | floatformat:2| intcomma }}</td>
						</tr><tr>
							<th>Payment Recieved</th> <td style="color: darkolivegreen">{{ shop.paymentrec | floatformat:2| intcomma }}</td>
						</tr><tr>
							<th>Outstanding Payment</th> <td style="color: red">{{ shop.outstandingpayment |floatformat:2 | intcomma }}</td>
						</tr><tr>
							<th>Total</th> <td><b>{{ shop.totaltobepaid | floatformat:2| intcomma  }}</b></td>
						</tr><tr>
							<th>Tenancy Start Day</th> <td>{{ shop.tenancystartdate  }}</td>
						</tr>

					</tbody>
				</table>

{#                <h1>View Payments Made</h1>#}
{#                <table class="">#}
{#                    <tbody>#}
{#                    <tr>#}
{#                        <td> <a href="{% url 'tenantRecords:statements' shop.number%}"> Payments</a></td>#}
{#                    </tr><tr>#}
{#                        <td> <a href="{% url 'tenantRecords:revisions' shop.number %}"> View Revisions</a></td>#}
{#                    </tr>#}
{#                    </tbody>#}
{#                </table>#}

                <h1 style="font-size: 18pt">Bank Details For Payment</h1>
                <table class="">
                    <tbody>
                    <tr>
                        <td> Bank Name: GTBank</td> <td> Account Name: The Capital Hub </td> <td> Account Number: 0216194787 </td>
                    </tr>
                    </tbody>
                </table>

            <p style="font-size: 14pt">
                Yours faithfully,
                <br>
                <br>
                <br>
                <br>
                Fatima I. Galaudu
                <br>
                <i><b>Managing Director</b></i>
            </p>




			</div>

		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="{% static "tenantRecords/js/jquery.stickyheader.js" %}"></script>
		<script src="{% static "tenantRecords/js/jquery.ba-throttle-debounce.min.js" %}"></script>
	</body>
</html>