apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    re_path('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/options$', login_required(views.DetailView.as_view()), name='detail'),
    re_path('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/summary$', login_required(views.SummaryView.as_view()), name='summary'),
    re_path('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/profile$', login_required(views.ShopProfileView.as_view()), name='profile'),
    re_path('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/receipt$', login_required(views.ReceiptView.as_view()), name='receipt'),
    re_path('^(?P<pk>\d+[A-Z]?.?[0-9]*?[a-z]*?)/tenancy_details$', login_required(views.TenancyDetailsView.as_view()), name='tenancy_details'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]
app_name = 'home'

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("old/", include("tenantRecords.urls")),  # tenant records
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls", namespace='home')),           # UI Kits Html files
]

apps/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

apps/home/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from tenantRecords import models as tenant_models
from django.db.models import Sum
from datetime import date, timedelta, datetime
from calendar import monthrange
import pendulum
from django.views import generic
from tenantRecords.models import Shop, Payment


@login_required(login_url="/login/")
def index(request):

    today = date.today()
    pendulum_today = pendulum.now()

    last_day_of_month = monthrange(today.year, today.month)[1]

    this_month = [pendulum_today.start_of('month') , pendulum_today.end_of('month')]

    last_month = [today.replace(month=today.month-1, day=1) , today.replace(month=today.month-1, day=monthrange(today.year, today.month-1)[1])]

    # this_week = [today - timedelta(days=7), today.strftime("%Y-%m-%d")]
    this_week = [pendulum_today.start_of('week'), pendulum_today.end_of('week')]
    last_week = [(today - timedelta(days=14)), (today - timedelta(days=7))]
    this_year = [today.replace(day=1).replace(month=1) , today.replace(day=31).replace(month=12)]

    context = {'segment': 'index',
               'is_upper_mgt': True if request.user.get_username() in [''] else False,
               'shops' : tenant_models.Shop.objects.all(),
               'payments': tenant_models.Payment.objects.all().order_by('-paymentdate')[:30],
               'years_payments': tenant_models.Payment.objects.filter(paymentdate__range=this_year).aggregate(Sum('amount'))['amount__sum'],
               'weeks_payments': tenant_models.Payment.objects.filter(paymentdate__range=this_week).aggregate(Sum('amount'))['amount__sum'],
               'previous_weeks_payments': tenant_models.Payment.objects.filter(paymentdate__range=last_week).aggregate(Sum('amount'))['amount__sum'],
               'sc_expenses_month': tenant_models.SCExpense.objects.filter(date__range=this_month).aggregate(Sum('amount'))['amount__sum'],
               'sc_expenses_last_month': tenant_models.SCExpense.objects.filter(date__range=last_month).aggregate(Sum('amount'))['amount__sum'],
               'sc_expenses_week': tenant_models.SCExpense.objects.filter(date__range=this_week).aggregate(Sum('amount'))['amount__sum'],
               'percent': 50,
               }

    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context, request))


@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]

        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('home/page-500.html')
        return HttpResponse(html_template.render(context, request))


class DetailView(generic.DetailView):
    model = Shop
    template_name = 'home/invoice.html'


class SummaryView(generic.DetailView):
    model = Shop
    template_name = 'home/invoice.html'


class ShopProfileView(generic.DetailView):
    model = Shop
    template_name = 'home/Profile.html'


class ReceiptView(generic.DetailView):
    model = Payment
    template_name = 'home/invoice.html'


class TenancyDetailsView(generic.DetailView):
    model = Shop
    template_name = 'home/tenancy_details.html'

apps/templates/home/data_table.html
{% extends 'partials/base.html' %}
{% load static %}

{% block extra_css %}

        <!-- DataTables -->
        <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'libs/datatables.net-select-bs4/css//select.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

        <!-- Responsive datatable examples -->
        <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

{% endblock extra_css %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Buttons Example</h4>
                <p class="card-title-desc">The Buttons extension for DataTables
                    provides a common set of options, API methods and styling to display
                    buttons on a page that will interact with a DataTable. The core library
                    provides the based framework upon which plug-ins can built.
                </p>

                <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Age</th>
                        <th>Start date</th>
                        <th>Salary</th>
                    </tr>
                    </thead>


                    <tbody>
                    <tr>
                        <td>Tiger Nixon</td>
                        <td>System Architect</td>
                        <td>Edinburgh</td>
                        <td>61</td>
                        <td>2011/04/25</td>
                        <td>$320,800</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

{% endblock content %}

{% block extra_javascript %}
        <!-- Required datatable js -->
        <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
        <!-- Buttons examples -->
        <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
        <script src="{% static 'libs/jszip/jszip.min.js' %}"></script>
        <script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
        <script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
        <script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
        <script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
        <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

        <script src="{% static 'libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
        <script src="{% static 'libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>

        <!-- Responsive examples -->
        <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

        <!-- Datatable init js -->
        <script src="{% static 'js/pages/datatables.init.js' %}"></script>
{% endblock extra_javascript %}

apps/templates/home/invoice.html
{% load humanize %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Amaro Dashboard - Receipt</title>

		<style>
			.invoice-box {
				max-width: 800px;
				margin: auto;
				padding: 30px;
				border: 1px solid #eee;
				box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
				font-size: 16px;
				line-height: 24px;
				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
				color: #555;
			}

			.invoice-box table {
				width: 100%;
				line-height: inherit;
				text-align: left;
			}

			.invoice-box table td {
				padding: 5px;
				{#vertical-align: top;#}
			}

			.invoice-box table tr td:nth-child(2) {
				text-align: right;
			}

			.invoice-box table tr.top table td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.top table td.title {
				font-size: 45px;
				line-height: 45px;
				color: #333;
			}

			.invoice-box table tr.information table td {
				padding-bottom: 40px;
			}

			.invoice-box table tr.heading td {
				background: #eee;
				border-bottom: 1px solid #ddd;
				font-weight: bold;
			}

			.invoice-box table tr.details td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.item td {
				border-bottom: 1px solid #eee;
			}

			.invoice-box table tr.item.last td {
				border-bottom: none;
			}

			.invoice-box table tr.total td:nth-child(2) {
				border-top: 2px solid #eee;
				font-weight: bold;
			}

			@media only screen and (max-width: 600px) {
				.invoice-box table tr.top table td {
					width: 100%;
					display: block;
					text-align: center;
				}

				.invoice-box table tr.information table td {
					width: 100%;
					display: block;
					text-align: center;
				}
			}

			/** RTL **/
			.invoice-box.rtl {
				direction: rtl;
				font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
			}

			.invoice-box.rtl table {
				text-align: right;
			}

			.invoice-box.rtl table tr td:nth-child(2) {
				text-align: left;
			}
		</style>
	</head>

	<body>
		<div class="invoice-box">
			<table cellpadding="0" cellspacing="0">
				<tr class="top">
					<td colspan="2">
						<table>
							<tr>
								<td class="title">
									<img src="/static/assets/img/favicon.png" style="width: 100%; max-width: 300px" />
								</td>

								<td>
									For Invoice #: {{payment.shop.number}}<br />
									Created: {{payment.createddate}}<br />
{#									Due: {{payment.shop.tenancystartdate}}#}
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="information">
					<td colspan="2">
						<table>
							<tr>
								<td>
									Suite {{ payment.shop.number }}<br />
									{{payment.shop.tenant.houseaddress}}<br />
									Nigeria
								</td>

								<td>
									Suite 401<br />
									The capital Hub<br />
									Plot 272 Ahmadu Bello Way<br />
									Mabushi, Abuja<br />
									Nigeria
								</td>
							</tr>
						</table>
					</td>
				</tr>
                {% if payment.method %}
				<tr class="heading">
					<td>Payment Method</td>

					<td>{{payment.method}}</td>
				</tr>


				<tr class="details">
					<td>{{payment.method}}</td>

					<td>{{payment.amount}}</td>
				</tr>
                {% endif %}

				<tr class="heading">
					<td>Item</td>

					<td>Amount</td>
				</tr>

				<tr class="item">
					<td>Rent Payment on  {{ payment.paymentdate }}</td>

					<td>{{payment.amount | intcomma}}</td>
				</tr>



				<tr class="total">
					<td></td>
					<td>Total: {{payment.amount | intcomma}}</td>
				</tr>
			</table>
		</div>
	</body>
</html>

apps/templates/home/page-403.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <section>
    <div class="page-header section-height-75">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
            <div class="card card-plain mt-8">
              <div class="card-header pb-0 text-left bg-transparent">
                <h3 class="font-weight-bolder text-danger text-gradient">
                    Error 403
                </h3>
                <p class="mb-0 text-danger">
                    Access Denied - If the problem persist, please access support.
                </p>
              </div>
              <div class="card-body">
                  <div class="text-center">
                    <a type="button" href="/" class="btn bg-gradient-info w-100 mt-4 mb-0">HOME</a>
                  </div>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Contact 
                  <a href="#" class="text-info text-gradient font-weight-bold">Support</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
              <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('/static/assets/img/curved-images/curved6.jpg')"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>

{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <section>
    <div class="page-header section-height-75">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
            <div class="card card-plain mt-8">
              <div class="card-header pb-0 text-left bg-transparent">
                <h3 class="font-weight-bolder text-danger text-gradient">
                    Error 404
                </h3>
                <p class="mb-0 text-danger">
                    Page not found - If the problem persist, please access support.
                </p>
              </div>
              <div class="card-body">
                  <div class="text-center">
                    <a type="button" href="/" class="btn bg-gradient-info w-100 mt-4 mb-0">HOME</a>
                  </div>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Contact 
                  <a href="#" class="text-info text-gradient font-weight-bold">Support</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
              <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('/static/assets/img/curved-images/curved6.jpg')"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>

{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <section>
    <div class="page-header section-height-75">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
            <div class="card card-plain mt-8">
              <div class="card-header pb-0 text-left bg-transparent">
                <h3 class="font-weight-bolder text-danger text-gradient">
                    Error 500
                </h3>
                <p class="mb-0 text-danger">
                    Server Error - If the problem persist, please access support.
                </p>
              </div>
              <div class="card-body">
                  <div class="text-center">
                    <a type="button" href="/" class="btn bg-gradient-info w-100 mt-4 mb-0">HOME</a>
                  </div>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Contact 
                  <a href="#" class="text-info text-gradient font-weight-bold">Support</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
              <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('/static/assets/img/curved-images/curved6.jpg')"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>

{% endblock javascripts %}

apps/templates/home/profile.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    {% load humanize %}

    <div class="container-fluid">
      <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('/static/assets/img/curved-images/curved0.jpg'); background-position-y: 50%;">
        <span class="mask bg-gradient-primary opacity-6"></span>
      </div>
      <div class="card card-body blur shadow-blur mx-4 mt-n6">
        <div class="row gx-4">
          <div class="col-auto">
            <div class="avatar avatar-xl position-relative">
              <img src="/static/assets/img/bruce-mars.jpg" alt="..." class="w-100 border-radius-lg shadow-sm">
              <a href="javascript:;" class="btn btn-sm btn-icon-only bg-gradient-light position-absolute bottom-0 end-0 mb-n2 me-n2">
                <i class="fa fa-pen top-0" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Image"></i>
              </a>
            </div>
          </div>
          <div class="col-auto my-auto">
            <div class="h-100">
              <h5 class="mb-1">
                {{shop.tenant.name}} - {{shop.number}}
              </h5>
              <p class="mb-0 font-weight-bold text-sm">
                {{shop.businessname}}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid py-4">
    
      <div class="row my-3">
        <div class="col-12 col-xl-12">
          <div class="card mb-4">
            <div class="card-header pb-0 p-3">
              <div class="row">
                <div class="col-md-8 d-flex align-items-center">
                  <h6 class="mb-0">Partner Information</h6>
                </div>
                <div class="col-md-4 text-right">
                  <a href="javascript:;">
                    <i class="fas fa-user-edit text-secondary text-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Profile"></i>
                  </a>
                </div>
              </div>
            </div>
            <div class="card-body p-3">
{#              <p class="text-sm">#}
{#                Hi, I’m Alec Thompson, Decisions: If you can’t decide, the answer is no. If two equally difficult paths, choose the one more painful in the short term (pain avoidance is creating an illusion of equality).#}
{#              </p>#}
              <ul class="list-group">
                <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Full Name:</strong> &nbsp; {{shop.tenant.name}}</li>
                <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Mobile:</strong> &nbsp; {{shop.tenant.phonenumber}}</li>
                <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Email:</strong> &nbsp; {{shop.tenant.email}}</li>
                <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Location:</strong> &nbsp; {{shop.tenant.houseaddress}}</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
        <div class="col-lg-8">
          <div class="card my-4">
            <div class="card-header pb-0 px-3">
              <h6 class="mb-0">Tenancy History</h6>
            </div>
            <div class="card-body pt-4 p-3">
              <ul class="list-group">
                  {% for tenancy in shop.tenant.shops.all reversed %}
                <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                  <div class="d-flex flex-column">
                    <h6 class="mb-3 text-sm">{{tenancy.number}}</h6>
                    <span class="mb-2 text-xs">Total Bill: <span class="text-dark font-weight-bold ms-2">{{tenancy.totaltobepaid | intcomma}}</span></span>
                    <span class="mb-2 text-xs">Suite Number <span class="text-dark ms-2 font-weight-bold">{{tenancy.suitenumber}}</span></span>
                    <span class="text-xs">Invoice Number: <span class="text-dark ms-2 font-weight-bold">{{tenancy.number}}</span></span>
                      <span class="mb-2 text-xs">Outstanding Bill: <span class="text-dark font-weight-bold ms-2">{{tenancy.outstandingpayment| intcomma}}</span></span>

                  </div>
                  <div class="ms-auto">
                    <a  href="/admin/tenantRecords/shop/{{ shop.number}} "
                            class="btn btn-link text-dark px-3 mb-0"><i class="fas fa-pencil-alt text-dark me-2" aria-hidden="true"></i>Edit</a>
                      <a  href="{% url 'home:tenancy_details' shop.number %}"
                            class="btn btn-link text-dark px-3 mb-0"><i class="fa fa-eye text-dark me-2" aria-hidden="true"></i>View</a>
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>



          <div class="col-lg-4">
          <div class="card">
            <div class="card-header pb-0 p-3">
              <div class="row">
                <div class="col-md-6 d-flex align-items-center">
                  <h6 class="mb-0">Payment History</h6>
                </div>
                <div class="col-md-6 text-right">
                  <button class="btn btn-outline-primary btn-sm mb-0">View All</button>
                </div>
              </div>
            </div>
            <div class="card-body p-3">
              <ul class="list-group">
              {% for shop_ in shop.tenant.shops.all reversed %}
                  {% for payment in shop_.payment.all reversed %}
                <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                  <div class="d-flex flex-column">
                    <h6 class="mb-1 text-dark font-weight-bold text-sm">{{ payment.paymentdate }}</h6>
                    <span class="text-xs">{{payment.id}}</span>
                  </div>
                  <div class="d-flex align-items-center text-sm">
                    {{payment.amount | intcomma}}
                      <a href="{% url 'home:receipt' payment.id %}">
                    <button class="btn btn-link text-dark text-sm mb-0 px-0 ms-4"><i class="fas fa-file-pdf text-lg me-1"></i> RCT</button>
                          </a>
                  </div>
                </li>
                  {% endfor %}
              {% endfor %}
              </ul>
            </div>
          </div>
        </div>

        </div>



      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  
{% endblock javascripts %}

apps/templates/home/sign-in.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Sign IN {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <section>
    <div class="page-header section-height-75">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
            <div class="card card-plain mt-8">
              <div class="card-header pb-0 text-left bg-transparent">
                <h3 class="font-weight-bolder text-info text-gradient">Welcome back</h3>
                <p class="mb-0">Enter your email and password to sign in</p>
              </div>
              <div class="card-body">
                <form role="form text-left">
                  <label>Email</label>
                  <div class="mb-3">
                    <input type="email" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="email-addon">
                  </div>
                  <label>Password</label>
                  <div class="mb-3">
                    <input type="email" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="password-addon">
                  </div>
                  <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="rememberMe" checked="">
                    <label class="form-check-label" for="rememberMe">Remember me</label>
                  </div>
                  <div class="text-center">
                    <button type="button" class="btn bg-gradient-info w-100 mt-4 mb-0">Sign in</button>
                  </div>
                </form>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Don't have an account?
                  <a href="/sign-up.html" class="text-info text-gradient font-weight-bold">Sign UP</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
              <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('/static/assets/img/curved-images/curved6.jpg')"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>

{% endblock javascripts %}